### ISSUE TITLE
Error when Setting Up `bench_runner` on EC2 Instance

### ISSUE THREAD

**Issue by MAMV3x3** [MLH-Fellowship/cinder-benchmarks#8]
## Description
When attempting to set up `bench_runner` to run pyperformance benchmarks on an EC2 instance for the cinder repo, I encountered an AssertionError during the installation process.

### Steps to reproduce

1. Followed the instructions provided by the Faster CPython project's Benchmarking tools.
2. Created an EC2 instance.
3. Set up a fresh repository as per documentation: [cinder_bench_runner](https://github.com/MLH-Fellowship/cinder_bench_runner)
4. Added git+https://github.com/faster-cpython/bench_runner@v0.2.2#egg=bench_runner to a requirements.txt file.
5. Installed the requirements using python -m pip install -r requirements.txt.
6. Executed python3 -m bench_runner.scripts.install.

### Expected Behavior:
The bench_runner should set up without errors, generating necessary files in .github/workflows and other configurations at the root of the repository.

## Actual Behavior:
Encountered the following error:
```bash
❯ python -m bench_runner.scripts.install
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/mamv3x3/cinder_bench_runner/venv/lib/python3.10/site-packages/bench_runner/scripts/install.py", line 161, in <module>
    main(args.check)
  File "/home/mamv3x3/cinder_bench_runner/venv/lib/python3.10/site-packages/bench_runner/scripts/install.py", line 139, in main
    generator(path, WORKFLOW_PATH / (path.name[:-8] + ".yml"), check)
  File "/home/mamv3x3/cinder_bench_runner/venv/lib/python3.10/site-packages/bench_runner/scripts/install.py", line 108, in generate_benchmark
    available_runners = [r for r in runners.get_runners() if r.available]
  File "/home/mamv3x3/cinder_bench_runner/venv/lib/python3.10/site-packages/bench_runner/runners.py", line 39, in get_runners
    assert len(runners)
AssertionError
```
Would appreciate any help or guidance to resolve this issue!

**Comment by MAMV3x3** [comment]
It seems that the `bench_runner` installation script may be expecting a runner to be already set up. The error suggests it's attempting to identify available runners but isn't finding any, leading to the `AssertionError`. I'll try setting up the GitHub Actions self-hosted runner first and then rerun the installation script to see if it resolves the issue.

**Comment by MAMV3x3** [comment]
This issue has been resolved, as documented in the steps provided in #9. Closing this issue now. Thank you for the insights and assistance!
